### ISSUE TITLE
Bug - Empty items are drawn on on dragging

### ISSUE THREAD

**Issue by flaringapp** [ernestoyaquello/DragDropSwipeRecyclerview#33] opened 2019-10-05 12:52 UTC
I faced a strange bug. I have grid recycler (3 cols) with for example 50 draggable and 50 non-draggable items. When I'm dragging an item to the botom and release after the point where **last draggable item goes out of the screen and gets recycled**, scroll up to the place of last draggable position (where my dragged view is located now), I'm seeing 3 empty cells
![image](https://user-images.githubusercontent.com/35672654/66255072-0eb7b600-e788-11e9-8d42-ba8b72aaaa6d.png)

**Comment by ernestoyaquello** [comment] 2019-10-07 09:54
This certainly seems very strange. If you have looked further into the issue and know why it might be happening, any information would be highly appreciated. Also, a reproduction project would be great. Thanks!

**Comment by ernestoyaquello** [comment] 2019-10-27 11:08
Hey, any news on this?

**Comment by ernestoyaquello** [comment] 2019-11-07 14:17
Since I cannot reproduce it and there has been no news on it for more than a month, I will close the issue. Please come back to me if you think it should be reopened.

**Closed by ernestoyaquello** 2019-11-07 14:17 UTC
Labels: bug
