### ISSUE TITLE
Drag and drop with different viewtypes

### ISSUE THREAD

**Issue by paolovalerdi** [ernestoyaquello/DragDropSwipeRecyclerview#23] opened 2019-05-22 16:03 UTC
Currently, drag-n-drop isn't working quite well when one has different view types. You can still drag items of the same view type but when "jumping" from one to another the animation just cuts off.
https://imgur.com/gallery/HrkAjj6

**Comment by ernestoyaquello** [comment] 2019-05-25 10:18
I am currently using this library in a project in which I have different item types, and everything works just fine. Would you be able to provide a reproduction repo so I can look into your issue?

**Comment by paolovalerdi** [comment] 2019-05-25 15:41
Sure there it is: https://github.com/paolovalerdi/DragAndDrop

**Comment by ernestoyaquello** [comment] 2019-05-25 19:38
Thanks, I will look into it.

**Comment by ernestoyaquello** [comment] 2019-05-25 20:41
I am afraid that overriding `getItemViewType()` to return different types depending on the item position will always cause this issue to happen. The problem is that the recyclerview will detect that the item you are dragging has a new type as you move it, which will trigger the re-rendering of its viewholder (since its type has changed, the item needs to be entirely rebound).

This is a relatively common problem, but I haven't found any solutions for it, nor can I think of a good, generic one that I could implement in the library.

For the time being, I think you could achieve the same results in your app without overriding the method `getItemViewType()`. Instead, you could get the item type manually:

#### `Adapter`
```kotlin
// Avoiding this implementation because it is problematic
//override fun getItemViewType(position: Int): Int = when {
//    position < current -> HISTORY
//    position == current -> CURRENT
//    else -> UP_NEXT
//}

...

override fun onBindViewHolder(item: Song, viewHolder: ViewHolder, position: Int) {
    val itemType = getItemTypeFromPosition(position)
    val alpha = if (itemType == HISTORY || itemType == CURRENT) 0.5f else 1f
    viewHolder.dragIcon.alpha = alpha
    viewHolder.text.alpha = alpha
    viewHolder.title.alpha = alpha
    viewHolder.title.text = item.title
    viewHolder.text.text = item.artist
}

private fun getItemTypeFromPosition(position: Int): Int = when {
    position < current -> HISTORY
    position == current -> CURRENT
    else -> UP_NEXT
}
```

To make sure this works properly, you have to notify your adapter about changes whenever an item gets dropped by the user:

#### `MainActivity`
```kotlin
...

private lateinit var mAdapter: Adapter

private val mDragListener = object : OnItemDragListener<Song> {
    override fun onItemDragged(previousPosition: Int, newPosition: Int, item: Song) {
        // Nothing to do here
    }

    override fun onItemDropped(initialPosition: Int, finalPosition: Int, item: Song) {
        // Notify about changes to make sure the moved items are rendered
        // one way or another depending on their new position in the list
        mAdapter.notifyDataSetChanged()
    }
}

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    mAdapter = Adapter(5, items)
    recyclerView.apply {
        adapter = mAdapter
        layoutManager = LinearLayoutManager(this@MainActivity)
        orientation = DragDropSwipeRecyclerView.ListOrientation.VERTICAL_LIST_WITH_VERTICAL_DRAGGING
        dragListener = mDragListener
    }
}
```

With these changes, your app will hopefully have the expected behaviour!

**Comment by ernestoyaquello** [comment] 2019-05-25 21:16
I tested the alternative solution in your reproduction repository and it works, so I will now close the issue. Please let me know if you have any other problem or need further help and I will reopen it if necessary.

**Closed by ernestoyaquello** 2019-05-25 21:16 UTC
Labels: wontfix

**Comment by paolovalerdi** [comment] 2019-05-25 22:44
Yeah basically this was my workaround, but I was curious if this was an issue with the library or something. But I've tested with other implementations and the issue is still there.
