### ISSUE TITLE
Long Click Event not fired while refresh items short periodically 

### ISSUE THREAD

**Issue by dreamwork09** [ernestoyaquello/DragDropSwipeRecyclerview#63] opened 2021-06-27 02:52 UTC
Thanks for your great library.
I have implemented my fragments which shows live prices with your recyclerview.
But I have a problem with item long click listener.
The issue is that item long click events are not fired when refresh items per 500ms or less time.
How can I solve this issue?

Best.

**Comment by ernestoyaquello** [comment] 2021-07-14 19:53
I am not sure what you mean because I don't know all the details of your implementation, but the long click functionality works fine in the library, so it is likely something caused by your app. I will close the issue for now, but if you can provide a sample app where I can reproduce the issue, I will re-open it and try to apply the necessary fixes.

**Closed by ernestoyaquello** 2021-07-14 19:53 UTC
