### ISSUE TITLE
Crash - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rescalon34** [ernestoyaquello/DragDropSwipeRecyclerview#28] opened 2019-08-25 21:32 UTC
PID: 28622
    java.lang.ArrayIndexOutOfBoundsException: length=6; index=-1
        at java.util.ArrayList.get(ArrayList.java:413)
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeAdapter.onIsDraggingImpl(DragDropSwipeAdapter.kt:571)
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeAdapter.access$onIsDraggingImpl(DragDropSwipeAdapter.kt:26)
        at com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeAdapter$itemLayoutPositionListener$1.onPositionChanged(DragDropSwipeAdapter.kt:344)
        at com.ernestoyaquello.dragdropswiperecyclerview.util.DragDropSwipeTouchHelper.onChildDrawImpl(DragDropSwipeTouchHelper.kt:211)
        at com.ernestoyaquello.dragdropswiperecyclerview.util.DragDropSwipeTouchHelper.onChildDraw(DragDropSwipeTouchHelper.kt:159)
        at androidx.recyclerview.widget.ItemTouchHelper$Callback.onDraw(ItemTouchHelper.java:1983)
        at androidx.recyclerview.widget.ItemTouchHelper.onDraw(ItemTouchHelper.java:561)
        at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4284)
        at android.view.View.draw(View.java:18410)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4219)
        at android.view.View.updateDisplayListIfDirty(View.java:17388)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.updateDisplayListIfDirty(View.java:17383)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.draw(View.java:18413)
        at android.view.View.updateDisplayListIfDirty(View.java:17388)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:18413)
        at android.view.View.updateDisplayListIfDirty(View.java:17388)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.updateDisplayListIfDirty(View.java:17383)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.updateDisplayListIfDirty(View.java:17383)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.updateDisplayListIfDirty(View.java:17383)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.updateDisplayListIfDirty(View.java:17383)
        at android.view.View.draw(View.java:18172)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3969)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3755)
        at android.view.View.draw(View.java:18413)
        at com.android.internal.policy.DecorView.draw(DecorView.java:967)
        at android.view.View.updateDisplayListIfDirty(View.java:17388)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:722)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:728)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:836)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3181)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2565)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
2019-08-25 15:29:06.805 28622-28622/com.example.sv.testingApp E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:734)
        at android.view.Choreographer.doFrame(Choreographer.java:670)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by rescalon34** [comment] 2019-08-25 21:38
Hello @ernestoyaquello I think this issue was already solved but I'm able to reproduce it just by "spamming" the draw and drop icon.

Not sure if this will help you guys but just FYI I'm calling `notifyDataSetChanged()` on onItemDropped and calling nothing on `onItemDragged()`.

**Comment by ernestoyaquello** [comment] 2019-10-03 12:48
Thanks for letting me know, I will take a look as soon as I have time.

**Comment by ernestoyaquello** [comment] 2019-10-07 13:56
I am not able to reproduce the issue in the sample app, so I think it might be related to the call you are doing to `notifyDataSetChanged()` inside `onItemDropped()`. That call is incorrect because, by the time `onItemDropped()` has been invoked, the changes have already been notified to the list. Please remove that unnecessary call and let me know how it goes.

**Comment by ernestoyaquello** [comment] 2019-10-07 14:38
Just in case, I have added a check to stop this exception from happening again. It will be included in the next release of the library.

**Closed** 2019-10-07 15:18 UTC
Labels: bug

**Comment by rescalon34** [comment] 2019-10-13 20:50
don't worry @ernestoyaquello it's ok, I hope you've enjoyed your holidays! 
about the crash, I just removed notifyDataSetChanged() as you suggested and also tried the new release version, it works fine 👍 thanks for adding the check.
