### ISSUE TITLE
disableSwipeDirection & enableSwipeDirection not working as expected

### ISSUE THREAD

**Issue by fourofspades** [ernestoyaquello/DragDropSwipeRecyclerview#59] opened 2021-04-30 11:21 UTC
In my OnCreateView fragment, I am setting these properties based on a "lock UI" preference, which prevents swiping left/right/reordering.

In short, I need to restart the activity for this to take effect, it doesn't work setting this within the fragment OnCreateView, even though the code paths are being executed at the expected time.  Is there something else I need to do here, or is this a bug?

Thanks.

```java
_binding.list.setOrientation(DragDropSwipeRecyclerView.ListOrientation.VERTICAL_LIST_WITH_VERTICAL_DRAGGING);

if (PreferenceManager.getDefaultSharedPreferences(getContext()).getBoolean("UI_LOCKED", false))
{
    _binding.list.disableSwipeDirection(DragDropSwipeRecyclerView.ListOrientation.DirectionFlag.LEFT);
    _binding.list.disableSwipeDirection(DragDropSwipeRecyclerView.ListOrientation.DirectionFlag.RIGHT);
}
else
{
    _binding.list.enableSwipeDirection(DragDropSwipeRecyclerView.ListOrientation.DirectionFlag.LEFT);
    _binding.list.enableSwipeDirection(DragDropSwipeRecyclerView.ListOrientation.DirectionFlag.RIGHT);
}
```

**Comment by ernestoyaquello** [comment] 2021-05-01 09:25
I have tried calling these methods both inside `onCreateView()` and inside `onViewCreated()` and they seem to work fine. In fact, I am using them in my own application within `onViewCreated()`. As long as you are calling them after the orientation of the list is set, they should work.

Do you mind providing a sample app where the issue is reproducible? Thanks!

**Comment by fourofspades** [comment] 2021-05-01 13:11
I think it's something related to automatic view binding creation, if I use FindViewByID, it appears to work (in the app I just wrote).

**Comment by fourofspades** [comment] 2021-05-01 16:02
OK, have worked around this by setting the enabled/disabled properties later.  It seems when using [viewbinding ](https://developer.android.com/topic/libraries/view-binding) in Java, something weird is going on.

**Comment by ernestoyaquello** [comment] 2021-05-02 16:54
It seems like the error was not exactly on the library, so I will close the issue. Glad to see you solved it!

**Closed by ernestoyaquello** 2021-05-02 16:54 UTC
Labels: question
