### ISSUE TITLE
[QUESTION]: Can it use with NestedScrollView ?

### ISSUE THREAD

**Issue by YaeBE** [ernestoyaquello/DragDropSwipeRecyclerview#62] opened 2021-06-08 10:06 UTC
when using it inside NestedScrollView the auto scroll not working. try to use android:fillViewport="true"
        android:orientation="vertical", requestDisallowInterceptTouchEvent with no success

**Comment by ernestoyaquello** [comment] 2021-06-09 12:39
Not sure about the details of your implementation, but the library should work in this scenario, I don't see why it wouldn't. Have you checked whether your code works when you replace the `DragDropSwipeRecyclerview` with a standard `Recyclerview`?

**Comment by YaeBE** [comment] 2021-06-09 12:41
Yes, when doing so and adding the properties on XML it works fine

**Comment by ernestoyaquello** [comment] 2021-06-09 12:44
So, I take it this is a problem that doesn't happen with a standard RecyclerView, but happens with the `DragDropSwipeRecyclerview`. I will investigate the issue, thanks for reporting it!

**Comment by ernestoyaquello** [comment] 2021-06-09 12:50
Sorry, I just tried wrapping the `DragDropSwipeRecyclerview` with a `NestedScrollView` and everything worked perfectly. If you are sure there isn't a problem with your implementation, could you please provide a sample app so I can reproduce the issue? Thanks!

**Comment by YaeBE** [comment] 2021-06-09 12:54
Have you tried to add a lot of items and then check the auto scroll?
The problem is with the auto scroll.
In Grid
I did the following:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  ***@***.***/activity_main">

  <androidx.core.widget.NestedScrollView
    android:id="@+id/nestedScrollView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginTop="20dp"
    android:layout_marginStart="20dp"
    android:layout_marginEnd="20dp"
    android:scrollbars="none"
    android:overScrollMode="never">

    <LinearLayout
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:orientation="vertical">


      <com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView
        android:id="@+id/list"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:nestedScrollingEnabled="false"
        android:visibility="visible"
        ***@***.***/behind_swiped_grid_list"
        ***@***.***/behind_swiped_grid_list_secondary"
        ***@***.***/list_item_grid_list_cardview"
        app:swiped_item_opacity_fades_on_swiping="true" />
    </LinearLayout>

  </androidx.core.widget.NestedScrollView>

</LinearLayout>


From: Julio Ernesto Rodríguez Cabañas ***@***.***>
Date: Wednesday, 9 June 2021 at 15:50
To: ernestoyaquello/DragDropSwipeRecyclerview ***@***.***>
Cc: YaeBE ***@***.***>, Author ***@***.***>
Subject: Re: [ernestoyaquello/DragDropSwipeRecyclerview] [QUESTION]: Can it use with NestedScrollView ? (#62)

Sorry, I just tried wrapping the DragDropSwipeRecyclerview with a NestedScrollView and everything worked perfectly. If you are sure there isn't a problem with your implementation, could you please provide a sample app so I can reproduce the issue? Thanks!

**Comment by ernestoyaquello** [comment] 2021-06-09 18:37
I assume you mean something like this `list.smoothScrollToPosition(position)` when you say "auto scroll"? If that's the case, the scroll won't work because the `RecyclerView` doesn't control the scrolling in this scenario; the `NestedScrollView` does.

To scroll to a certain item programmatically in your scenario, you will need to calculate the position and then call `nestedScrollView.smoothScrollTo(calculatedX, calculatedY)`.

Unless I am missing something (please let me know if I am), this is not an issue of the library, as this is the same behaviour a standard `RecyclerView` would have.

**Comment by ernestoyaquello** [comment] 2021-07-14 19:57
I will close this for now. If you can provide an example project where I can reproduce the issue and verify that is caused by the library, I will re-open it. I hope my previous message was of some help!

**Closed by ernestoyaquello** 2021-07-14 19:57 UTC
Labels: question
